services:
- type: pserv
  env: docker
  region: frankfurt # optional (defaults to oregon)
  plan: free # optional (defaults to starter)
  branch: main # optional (defaults to master)
  numInstances: 1
  healthCheckPath: /healthz
  name: your-app-ollama
  dockerContext: ./ollama
  dockerfilePath: ./ollama/Dockerfile
  plan: starter
  envVars:
    - key: OLLAMA_URL
      fromService:
      name: your-app-ollama
      type: pserv
      property: hostport
